import "server-only";
import { getServiceRoleClient } from '@/lib/supabase';
import type { InsSource } from './types';

/**
 * Determine whether a post was generated by CAP or composed manually.
 * Traverses: social_publish_attempts.bundle_post_id
 *   → social_post_variant.post_master_id
 *   → social_post_master.source_type
 *
 * Returns { source: 'cap' } if source_type = 'cap'.
 * Returns { source: 'composer' } otherwise.
 * capCampaignPostId is always null (V1 — no direct FK trail from bundle_post_id to cap_campaign_posts).
 */
export async function resolvePostSource(
  bundlePostId: string,
): Promise<{ source: InsSource; capCampaignPostId: string | null }> {
  const svc = getServiceRoleClient();

  const { data: attempt } = await svc
    .from('social_publish_attempts')
    .select('post_variant_id')
    .eq('bundle_post_id', bundlePostId)
    .maybeSingle();

  if (!attempt?.post_variant_id) {
    return { source: 'composer', capCampaignPostId: null };
  }

  const { data: variant } = await svc
    .from('social_post_variant')
    .select('post_master_id')
    .eq('id', attempt.post_variant_id)
    .maybeSingle();

  if (!variant?.post_master_id) {
    return { source: 'composer', capCampaignPostId: null };
  }

  const { data: master } = await svc
    .from('social_post_master')
    .select('source_type')
    .eq('id', variant.post_master_id)
    .maybeSingle();

  if (master?.source_type === 'cap') {
    return { source: 'cap', capCampaignPostId: null };
  }

  return { source: 'composer', capCampaignPostId: null };
}
