import "server-only";
import { getServiceRoleClient } from '@/lib/supabase';
import type { InsSource } from './types';

/**
 * Determine whether a post was generated by CAP or composed manually.
 *
 * V2 path (short-circuit): if social_post_drafts has a row with bundle_post_id
 * matching the given ID, return draft.source_type directly. This covers all V2
 * posts published after migration 0156 landed.
 *
 * V1 path (fallback): traverses social_publish_attempts.bundle_post_id
 *   → social_post_variant.post_master_id → social_post_master.source_type
 * Covers V1 posts and V2 posts published before migration 0156.
 *
 * capCampaignPostId is always null (no direct FK trail from bundle_post_id to
 * cap_campaign_posts in either model — kept for interface compatibility).
 */
export async function resolvePostSource(
  bundlePostId: string,
): Promise<{ source: InsSource; capCampaignPostId: string | null }> {
  const svc = getServiceRoleClient();

  // V2 path: check social_post_drafts first (migration 0155 added source_type,
  // migration 0156 added bundle_post_id).
  const { data: draft } = await svc
    .from('social_post_drafts')
    .select('source_type')
    .eq('bundle_post_id', bundlePostId)
    .maybeSingle();

  if (draft) {
    const source: InsSource = draft.source_type === 'cap' ? 'cap' : 'composer';
    return { source, capCampaignPostId: null };
  }

  // V1 path: traverse the legacy chain.
  const { data: attempt } = await svc
    .from('social_publish_attempts')
    .select('post_variant_id')
    .eq('bundle_post_id', bundlePostId)
    .maybeSingle();

  if (!attempt?.post_variant_id) {
    return { source: 'composer', capCampaignPostId: null };
  }

  const { data: variant } = await svc
    .from('social_post_variant')
    .select('post_master_id')
    .eq('id', attempt.post_variant_id)
    .maybeSingle();

  if (!variant?.post_master_id) {
    return { source: 'composer', capCampaignPostId: null };
  }

  const { data: master } = await svc
    .from('social_post_master')
    .select('source_type')
    .eq('id', variant.post_master_id)
    .maybeSingle();

  if (master?.source_type === 'cap') {
    return { source: 'cap', capCampaignPostId: null };
  }

  return { source: 'composer', capCampaignPostId: null };
}
