export const MSP_CYBERSEC_TOPIC_TAGS = [
  // Cybersecurity
  "ransomware",
  "phishing",
  "zero-trust",
  "incident-response",
  "compliance",
  "soc2",
  "iso27001",
  "gdpr",
  "hipaa",
  "endpoint-protection",
  "edr",
  "mdr",
  "siem",
  "xdr",
  "firewall",
  "vpn",
  "mfa",
  "identity-management",
  "cloud-security",
  // MSP business
  "msp-pricing",
  "msp-sales",
  "msp-marketing",
  "msp-recruitment",
  "team-culture",
  "client-onboarding",
  "sla",
  "ticketing",
  "rmm",
  "psa",
  "documentation",
  "pricing-model",
  // Customer-focused
  "business-continuity",
  "disaster-recovery",
  "backup",
  "cloud-migration",
  "office365",
  "azure",
  "aws",
  "gcp",
  "workplace-automation",
  "iot-security",
  "mobile-device-management",
  // Industry trends
  "ai-in-msp",
  "automation",
  "managed-detection",
  "cyber-insurance",
  "supply-chain-security",
  "vulnerability-management",
  "patch-management",
  // Soft topics
  "thought-leadership",
  "case-study",
  "customer-story",
  "team-news",
  "company-news",
  "product-launch",
  "event-announcement",
  "webinar",
  "hiring",
  "recognition",
  "partnership",
] as const;

export type MspCybersecTopicTag = (typeof MSP_CYBERSEC_TOPIC_TAGS)[number];

export const TOPIC_TAG_SET: ReadonlySet<string> = new Set(MSP_CYBERSEC_TOPIC_TAGS);
