import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";

import { E2E_TEST_SITE_PREFIX } from "./fixtures";
import { auditA11y, signInAsAdmin } from "./helpers";

// ---------------------------------------------------------------------------
// M13-4 — posts admin surface E2E.
//
// Scope:
//   1. List page renders with filter controls + seeded post visible
//   2. Detail page renders with title + slug + generated-HTML iframe
//   3. Preflight blocker copy surfaces when WP creds aren't configured
//      (the standard state for the E2E test site — it has no real WP
//      backend, so wpGetMe returns a network/404 blocker)
//   4. Unpublish confirm modal opens on a published post
//   5. auditA11y on each visited page
//
// Out of scope:
//   Actual publish path (needs a real or deeply-mocked WP REST server).
//   Unit tests cover the route-level publish/unpublish behavior via
//   global.fetch mocking in posts-publish-routes.test.ts.
// ---------------------------------------------------------------------------

function supabaseServiceClient() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    throw new Error(
      "SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY must be set for the E2E suite.",
    );
  }
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

async function findTestSite(): Promise<{ id: string }> {
  const svc = supabaseServiceClient();
  const { data, error } = await svc
    .from("sites")
    .select("id")
    .eq("prefix", E2E_TEST_SITE_PREFIX)
    .maybeSingle();
  if (error || !data) {
    throw new Error(
      `E2E test site not found (prefix ${E2E_TEST_SITE_PREFIX}): ${error?.message ?? "no row"}`,
    );
  }
  return { id: data.id as string };
}

async function seedDraftPost(opts: {
  siteId: string;
  slug: string;
  status?: "draft" | "published";
  wp_post_id?: number | null;
}): Promise<{ postId: string }> {
  const svc = supabaseServiceClient();
  const unique = `${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  const res = await svc
    .from("posts")
    .insert({
      site_id: opts.siteId,
      content_type: "post",
      title: `E2E post ${unique}`,
      slug: `${opts.slug}-${unique}`,
      design_system_version: 1,
      status: opts.status ?? "draft",
      generated_html: `<article><h1>Post ${unique}</h1><p>Body copy generated by the runner.</p></article>`,
      wp_post_id: opts.wp_post_id ?? null,
      published_at:
        opts.status === "published" ? new Date().toISOString() : null,
    })
    .select("id")
    .single();
  if (res.error || !res.data) {
    throw new Error(`seedDraftPost: ${res.error?.message}`);
  }
  return { postId: res.data.id as string };
}

test.describe("M13-4 posts — admin surface", () => {
  test.beforeEach(async ({ page }) => {
    await signInAsAdmin(page);
  });

  test("list page renders with filter controls + seeded posts", async ({
    page,
  }, testInfo) => {
    test.setTimeout(30_000);
    const site = await findTestSite();
    await seedDraftPost({ siteId: site.id, slug: "e2e-list-a" });
    await seedDraftPost({ siteId: site.id, slug: "e2e-list-b", status: "published" });

    await page.goto(`/admin/sites/${site.id}/posts`);
    await expect(page.getByRole("heading", { level: 1, name: /^posts$/i })).toBeVisible();
    await expect(page.getByRole("search", { name: /filter posts/i })).toBeVisible();
    await expect(page.getByLabel(/status/i)).toBeVisible();
    await expect(page.getByLabel(/search title/i)).toBeVisible();

    // Both seeded posts visible under the E2E site — may have other
    // pre-existing posts from prior tests in the shared stack, but the
    // seeded titles are unique.
    await expect(page.getByRole("heading", { name: /E2E post/ }).first()).toBeVisible();

    await auditA11y(page, testInfo);
  });

  test("detail page renders generated HTML in a sandboxed iframe + preflight surface", async ({
    page,
  }, testInfo) => {
    test.setTimeout(30_000);
    const site = await findTestSite();
    const { postId } = await seedDraftPost({
      siteId: site.id,
      slug: "e2e-detail",
    });

    await page.goto(`/admin/sites/${site.id}/posts/${postId}`);

    await expect(
      page.getByRole("heading", { level: 1, name: /E2E post/ }),
    ).toBeVisible();
    await expect(
      page.getByRole("heading", { name: /generated html/i }),
    ).toBeVisible();

    // The preview iframe exists with sandbox="" (security invariant).
    // We don't actually render inside it — just assert the element is
    // present with the right sandbox attribute.
    const iframe = page.locator('iframe[sandbox=""]');
    await expect(iframe).toBeVisible();

    // The E2E test site almost certainly doesn't have a real WP backend
    // behind its wp_url (it's a fixture site from global-setup).
    // preflight should surface some kind of blocker — either
    // REST_UNREACHABLE or AUTH_CAPABILITY_MISSING. Assert a blocker
    // banner is present rather than pinning the exact code.
    const blockerBanner = page.locator('[role="alert"]').filter({
      hasText: /can't publish|WordPress REST|WP Admin|app password/i,
    });
    // Either the blocker OR the Publish button is visible, depending on
    // the test site's WP state. We don't pin which, because that's
    // environment-dependent; either is acceptable.
    const publishOrBlocker = (await blockerBanner.count()) > 0
      ? "blocker"
      : (await page.getByRole("button", { name: /^publish to WP$/i }).count()) > 0
        ? "publish"
        : "neither";
    expect(publishOrBlocker).not.toBe("neither");

    await auditA11y(page, testInfo);
  });

  test("unpublish modal opens on a published post", async ({ page }) => {
    test.setTimeout(30_000);
    const site = await findTestSite();
    const { postId } = await seedDraftPost({
      siteId: site.id,
      slug: "e2e-unpub",
      status: "published",
      wp_post_id: 123,
    });

    await page.goto(`/admin/sites/${site.id}/posts/${postId}`);

    // Published post → unpublish button visible.
    await expect(
      page.getByRole("button", { name: /unpublish/i }),
    ).toBeVisible();
    await page.getByRole("button", { name: /unpublish/i }).click();

    // Confirm modal opens with destructive copy.
    await expect(
      page.getByRole("dialog", { name: /send this post to WP trash/i }),
    ).toBeVisible();
    await expect(
      page.getByText(/WordPress keeps it in Trash/i),
    ).toBeVisible();

    // Dismiss — don't actually unpublish (no real WP).
    await page.getByRole("button", { name: /^cancel$/i }).click();
    await expect(
      page.getByRole("dialog", { name: /send this post to WP trash/i }),
    ).not.toBeVisible();
  });
});
