import "server-only";

import type {
  AnthropicCallFn,
  AnthropicResponse,
} from "@/lib/anthropic-call";
import type {
  VisualRenderFn,
  VisualRenderResult,
} from "@/lib/visual-review";

// ---------------------------------------------------------------------------
// M12-6 — dummy Anthropic + visual-render stubs for E2E and preview
// environments.
//
// Mirrors the M3-3 processSlotDummy pattern: the cron tick routes to the
// real Anthropic path when ANTHROPIC_API_KEY is present, otherwise
// falls back to these deterministic stubs. That keeps the full
// concurrency loop, lease/heartbeat machinery, and state transitions
// exercised in CI without burning tokens.
//
// Determinism: output is a function of the Anthropic request's
// idempotency_key only. Two calls with the same key return the same
// response shape. That matches Anthropic's real 24h cache semantics
// and keeps resume-after-crash tests stable.
//
// These stubs DO NOT claim to validate prompt quality. They exist so
// the runner's orchestration is exercisable without Anthropic; the
// actual text/visual outputs are nonsense.
// ---------------------------------------------------------------------------

// 1×1 transparent PNG, base64. 68 bytes raw. Used for both viewport +
// full-page screenshots in the visual render stub.
const TINY_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgAAIAAAUAAeImBZsAAAAASUVORK5CYII=";

// Stub draft HTML — full <!DOCTYPE html> shell so the structural-
// completeness gate (lib/brief-runner.ts::runStructuralCompletenessCheck,
// 2026-04-28) accepts it. Real Anthropic responses are full HTML
// documents; the stub now mirrors that. Unique per idempotency key
// so critique_log entries don't collapse across passes.
function dummyDraftHtmlFor(idempotencyKey: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head><title>Stub</title></head>
<body><section data-stub-key="${idempotencyKey}"><h1>Stub draft</h1><p>Generated by brief-runner-dummy.</p></section></body>
</html>`;
}

function dummyCritiqueText(): string {
  return "- [stub] polish whitespace on the hero";
}

function dummyVisualCritiqueJson(): string {
  // Empty issues = clean exit on the first visual iteration.
  // runner interprets no severity-high → transition to awaiting_review
  // without revising.
  return [
    "```json",
    JSON.stringify({
      issues: [],
      overall_notes: "Stub critique — looks acceptable.",
    }),
    "```",
  ].join("\n");
}

function anchorReviseJson(): string {
  // The anchor page's final revise gets its conventions JSON by
  // convention. Runner extracts via extractConventionsFromRevise.
  // Full <!DOCTYPE html> shell so the structural-completeness gate
  // accepts the stub draft after the runner extracts the JSON.
  return [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head><title>Anchor</title></head>",
    "<body><section data-stub-anchor><h1>Anchor stub</h1></section></body>",
    "</html>",
    "",
    "```json",
    JSON.stringify({
      typographic_scale: "dummy-scale",
      section_rhythm: "alternating",
      hero_pattern: "image-left",
      tone_register: "direct",
    }),
    "```",
  ].join("\n");
}

/**
 * Dummy Anthropic caller. Keyed purely on the request's idempotency_key
 * + pass_kind so two identical requests always produce the same text.
 */
export const dummyAnthropicCall: AnthropicCallFn = async (req) => {
  const key = req.idempotency_key;
  let text: string;

  if (key.includes(":self_critique:")) {
    text = dummyCritiqueText();
  } else if (key.includes(":visual_critique:")) {
    text = dummyVisualCritiqueJson();
  } else if (key.includes(":revise:") && key.endsWith(":revise:2")) {
    // Anchor's final revise pass (number 2 = ANCHOR_EXTRA_CYCLES).
    // Emit the conventions JSON so the runner's anchor freeze step
    // has something to parse.
    text = anchorReviseJson();
  } else {
    // draft / revise / visual_revise — return plain stub HTML.
    text = dummyDraftHtmlFor(key);
  }

  const resp: AnthropicResponse = {
    id: `dummy-${key}`,
    model: req.model,
    content: [{ type: "text", text }],
    stop_reason: "end_turn",
    usage: {
      input_tokens: 100,
      output_tokens: 50,
      cache_creation_input_tokens: 0,
      cache_read_input_tokens: 0,
    },
  };
  return resp;
};

/**
 * Dummy visual render. Returns a 1×1 transparent PNG for both the
 * viewport-fit and full-page screenshots. The critique stub doesn't
 * look at the image bytes anyway — it only needs a payload the runner
 * can pass through to the dummyAnthropicCall.
 */
export const dummyVisualRender: VisualRenderFn = async () => {
  const result: VisualRenderResult = {
    viewport_png_base64: TINY_PNG_BASE64,
    full_page_png_base64: TINY_PNG_BASE64,
    viewport_bytes: 68,
    full_page_bytes: 68,
  };
  return result;
};
