/**
 * lib/component-registry.ts
 *
 * The complete component library for Opollo site generation.
 * 8 component types. 20 variants total. This is the complete v1 list.
 * No additions without a milestone decision.
 *
 * Field schemas copied from payloadcms/payload website template blocks (MIT).
 * Render HTML adapted from HyperUI (https://www.hyperui.dev) (MIT).
 *
 * CSS class naming: opollo-{ComponentType} opollo-{ComponentType}--{variant}
 * CSS classes are NEVER generated by the LLM.
 * All render functions use CSS variables, never inline styles or Tailwind.
 */

import type { ComponentRegistry, Fields, RenderTarget } from './types/page-document';

// ─── FIELD SCHEMAS (from Payload Website Template) ────────────────────────

const heroFields: Fields = {
  headline:    { type: 'text',     label: 'Headline' },
  subheadline: { type: 'textarea', label: 'Subheadline' },
  variant:     { type: 'radio',    label: 'Layout variant',
                 options: [
                   { label: 'Centred',      value: 'centered'    },
                   { label: 'Image right',  value: 'split-right' },
                   { label: 'Image left',   value: 'split-left'  },
                 ]},
  ctaVariant:  { type: 'select',   label: 'CTA button style',
                 options: [
                   { label: 'Primary', value: 'primary' },
                   { label: 'Ghost',   value: 'ghost'   },
                 ]},
};

const featuresFields: Fields = {
  heading:    { type: 'text',     label: 'Section heading' },
  subheading: { type: 'textarea', label: 'Subheading' },
  variant:    { type: 'radio',    label: 'Layout',
                options: [
                  { label: '3-column grid', value: 'grid-3' },
                  { label: '2-column grid', value: 'grid-2' },
                  { label: 'List',          value: 'list'   },
                ]},
  features: { type: 'array', label: 'Features',
              arrayFields: {
                title:       { type: 'text',     label: 'Title'       },
                description: { type: 'textarea', label: 'Description' },
                iconSlug:    { type: 'text',     label: 'Icon slug (e.g. "star", "check")' },
              }},
};

const ctaBannerFields: Fields = {
  heading:    { type: 'text',     label: 'Heading'    },
  subheading: { type: 'textarea', label: 'Subheading' },
  variant:    { type: 'radio',    label: 'Layout',
                options: [
                  { label: 'Full width', value: 'full-width' },
                  { label: 'Card',       value: 'card'       },
                  { label: 'Inline',     value: 'inline'     },
                ]},
};

const contentFields: Fields = {
  heading:   { type: 'text',     label: 'Heading'                          },
  body:      { type: 'textarea', label: 'Body text'                        },
  bodyRight: { type: 'textarea', label: 'Right column (two-column only)'   },
  variant:   { type: 'radio',    label: 'Layout',
               options: [
                 { label: 'Prose',       value: 'prose'      },
                 { label: 'Two column',  value: 'two-column' },
                 { label: 'With image',  value: 'with-image' },
               ]},
};

const testimonialFields: Fields = {
  heading:  { type: 'text',  label: 'Section heading' },
  variant:  { type: 'radio', label: 'Layout',
              options: [
                { label: 'Single large quote', value: 'single' },
                { label: '3-column grid',      value: 'grid'   },
              ]},
  testimonials: { type: 'array', label: 'Testimonials',
    arrayFields: {
      quote:   { type: 'textarea', label: 'Quote'        },
      author:  { type: 'text',     label: 'Author name'  },
      role:    { type: 'text',     label: 'Role / title' },
      company: { type: 'text',     label: 'Company'      },
    }},
};

const faqFields: Fields = {
  heading:  { type: 'text',  label: 'Section heading' },
  variant:  { type: 'radio', label: 'Layout',
              options: [
                { label: 'Accordion', value: 'accordion' },
                { label: 'List',      value: 'list'      },
              ]},
};

const statsFields: Fields = {
  heading:  { type: 'text',  label: 'Section heading' },
  variant:  { type: 'radio', label: 'Layout',
              options: [
                { label: 'Horizontal row', value: 'horizontal' },
                { label: 'Grid',           value: 'grid'       },
              ]},
  stats: { type: 'array', label: 'Stats',
           arrayFields: {
             value:  { type: 'text', label: 'Value (e.g. "98%" or "10k+")' },
             label:  { type: 'text', label: 'Label (e.g. "Client satisfaction")' },
           }},
};

const contactFields: Fields = {
  heading:    { type: 'text',     label: 'Heading'          },
  subheading: { type: 'textarea', label: 'Subheading'       },
  email:      { type: 'text',     label: 'Email address'    },
  phone:      { type: 'text',     label: 'Phone number'     },
  address:    { type: 'textarea', label: 'Physical address' },
  variant:    { type: 'radio',    label: 'Layout',
                options: [
                  { label: 'Contact form + details', value: 'form'    },
                  { label: 'Contact details only',   value: 'details' },
                ]},
};

// ─── HELPERS ─────────────────────────────────────────────────────────────────

function esc(s: unknown): string {
  if (s == null) return '';
  if (typeof s === 'object') return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;');
}

type CtaShape = { text?: string; url?: string; variant?: string };
type ImageShape = { url?: string; alt?: string };
type TestimonialShape = { quote?: string; author?: string; role?: string; company?: string };
type FaqShape = { question?: string; answer?: string };
type StatShape = { value?: string; label?: string };
type FeatureShape = { title?: string; description?: string; iconSlug?: string };

function ctaBtn(cta: CtaShape | undefined, fallbackVariant = 'primary'): string {
  if (!cta?.text) return '';
  const v = esc(cta.variant ?? fallbackVariant);
  return `<a href="${esc(cta.url ?? '#')}" class="opollo-btn opollo-btn--${v}">${esc(cta.text)}</a>`;
}

function checkIcon(): string {
  return `<span class="opollo-feature-icon" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="20" height="20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg></span>`;
}

function asArray<T>(v: unknown): T[] {
  return Array.isArray(v) ? (v as T[]) : [];
}

// ─── HERO ────────────────────────────────────────────────────────────────────

function renderHeroCentered(props: Record<string, unknown>, _t: RenderTarget): string {
  const id       = esc(props.id);
  const headline = esc(props.headline);
  const sub      = esc(props.subheadline);
  const cta      = props.cta as CtaShape | undefined;
  const btn      = ctaBtn(cta, esc(props.ctaVariant) || 'primary');
  return `<section class="opollo-Hero opollo-Hero--centered" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-Hero__body">
      <h1 class="opollo-h1">${headline}</h1>${sub ? `\n      <p class="opollo-lead">${sub}</p>` : ''}${btn ? `\n      <div class="opollo-Hero__actions">${btn}</div>` : ''}
    </div>
  </div>
</section>`;
}

function renderHeroSplitRight(props: Record<string, unknown>, _t: RenderTarget): string {
  const id       = esc(props.id);
  const headline = esc(props.headline);
  const sub      = esc(props.subheadline);
  const cta      = props.cta as CtaShape | undefined;
  const img      = props.image as ImageShape | undefined;
  const btn      = ctaBtn(cta, esc(props.ctaVariant) || 'primary');
  const imgHtml  = img?.url
    ? `<img src="${esc(img.url)}" alt="${esc(img.alt ?? '')}" class="opollo-img" loading="lazy">`
    : `<div class="opollo-img-placeholder" aria-hidden="true"></div>`;
  return `<section class="opollo-Hero opollo-Hero--split-right" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-Hero__split">
      <div class="opollo-Hero__text">
        <h1 class="opollo-h1">${headline}</h1>${sub ? `\n        <p class="opollo-lead">${sub}</p>` : ''}${btn ? `\n        <div class="opollo-Hero__actions">${btn}</div>` : ''}
      </div>
      <div class="opollo-Hero__media">${imgHtml}</div>
    </div>
  </div>
</section>`;
}

function renderHeroSplitLeft(props: Record<string, unknown>, _t: RenderTarget): string {
  const id       = esc(props.id);
  const headline = esc(props.headline);
  const sub      = esc(props.subheadline);
  const cta      = props.cta as CtaShape | undefined;
  const img      = props.image as ImageShape | undefined;
  const btn      = ctaBtn(cta, esc(props.ctaVariant) || 'primary');
  const imgHtml  = img?.url
    ? `<img src="${esc(img.url)}" alt="${esc(img.alt ?? '')}" class="opollo-img" loading="lazy">`
    : `<div class="opollo-img-placeholder" aria-hidden="true"></div>`;
  return `<section class="opollo-Hero opollo-Hero--split-left" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-Hero__split opollo-Hero__split--reversed">
      <div class="opollo-Hero__media">${imgHtml}</div>
      <div class="opollo-Hero__text">
        <h1 class="opollo-h1">${headline}</h1>${sub ? `\n        <p class="opollo-lead">${sub}</p>` : ''}${btn ? `\n        <div class="opollo-Hero__actions">${btn}</div>` : ''}
      </div>
    </div>
  </div>
</section>`;
}

// ─── FEATURES ────────────────────────────────────────────────────────────────

function featureItems(features: FeatureShape[], extraItemClass = ''): string {
  if (!features.length) return '';
  return features.map(f => `      <li class="opollo-Features__item${extraItemClass}">
        ${checkIcon()}
        <div class="opollo-Features__item-body">
          ${f.title ? `<h3 class="opollo-h3">${esc(f.title)}</h3>` : ''}
          ${f.description ? `<p>${esc(f.description)}</p>` : ''}
        </div>
      </li>`).join('\n');
}

function renderFeaturesGrid3(props: Record<string, unknown>, _t: RenderTarget): string {
  const id       = esc(props.id);
  const heading  = esc(props.heading);
  const sub      = esc(props.subheading);
  const features = asArray<FeatureShape>(props.features);
  return `<section class="opollo-Features opollo-Features--grid-3" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<div class="opollo-Features__header">\n      <h2 class="opollo-h2">${heading}</h2>${sub ? `\n      <p class="opollo-lead">${sub}</p>` : ''}\n    </div>` : ''}
    <ul class="opollo-Features__grid opollo-Features__grid--3" role="list">
${featureItems(features)}
    </ul>
  </div>
</section>`;
}

function renderFeaturesGrid2(props: Record<string, unknown>, _t: RenderTarget): string {
  const id       = esc(props.id);
  const heading  = esc(props.heading);
  const sub      = esc(props.subheading);
  const features = asArray<FeatureShape>(props.features);
  return `<section class="opollo-Features opollo-Features--grid-2" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<div class="opollo-Features__header">\n      <h2 class="opollo-h2">${heading}</h2>${sub ? `\n      <p class="opollo-lead">${sub}</p>` : ''}\n    </div>` : ''}
    <ul class="opollo-Features__grid opollo-Features__grid--2" role="list">
${featureItems(features)}
    </ul>
  </div>
</section>`;
}

function renderFeaturesList(props: Record<string, unknown>, _t: RenderTarget): string {
  const id       = esc(props.id);
  const heading  = esc(props.heading);
  const sub      = esc(props.subheading);
  const features = asArray<FeatureShape>(props.features);
  return `<section class="opollo-Features opollo-Features--list" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2">${heading}</h2>` : ''}${sub ? `\n    <p class="opollo-lead">${sub}</p>` : ''}
    <ul class="opollo-Features__stack" role="list">
${featureItems(features, ' opollo-Features__item--row')}
    </ul>
  </div>
</section>`;
}

// ─── CTA BANNER ──────────────────────────────────────────────────────────────

function renderCTABannerFullWidth(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const sub     = esc(props.subheading);
  const cta     = props.cta as CtaShape | undefined;
  const btn     = ctaBtn({ ...cta, variant: cta?.variant ?? 'secondary' });
  return `<section class="opollo-CTABanner opollo-CTABanner--full-width" data-opollo-id="${id}">
  <div class="opollo-CTABanner__bg">
    <div class="opollo-container opollo-section-padding">
      <div class="opollo-CTABanner__body">
        <h2 class="opollo-h2 opollo-CTABanner__heading">${heading}</h2>${sub ? `\n        <p class="opollo-lead opollo-CTABanner__lead">${sub}</p>` : ''}${btn ? `\n        ${btn}` : ''}
      </div>
    </div>
  </div>
</section>`;
}

function renderCTABannerCard(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const sub     = esc(props.subheading);
  const cta     = props.cta as CtaShape | undefined;
  const btn     = ctaBtn(cta);
  return `<section class="opollo-CTABanner opollo-CTABanner--card" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-CTABanner__card">
      <h2 class="opollo-h2">${heading}</h2>${sub ? `\n      <p class="opollo-lead">${sub}</p>` : ''}${btn ? `\n      <div class="opollo-CTABanner__actions">${btn}</div>` : ''}
    </div>
  </div>
</section>`;
}

function renderCTABannerInline(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const cta     = props.cta as CtaShape | undefined;
  const btn     = ctaBtn(cta);
  return `<section class="opollo-CTABanner opollo-CTABanner--inline" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-CTABanner__row">
      <p class="opollo-CTABanner__inline-text">${heading}</p>${btn ? `\n      ${btn}` : ''}
    </div>
  </div>
</section>`;
}

// ─── CONTENT ─────────────────────────────────────────────────────────────────

function renderContentProse(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const body    = esc(props.body);
  return `<section class="opollo-Content opollo-Content--prose" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-Content__prose">
      ${heading ? `<h2 class="opollo-h2">${heading}</h2>` : ''}
      ${body ? `<div class="opollo-Content__body"><p>${body}</p></div>` : ''}
    </div>
  </div>
</section>`;
}

function renderContentTwoColumn(props: Record<string, unknown>, _t: RenderTarget): string {
  const id         = esc(props.id);
  const heading    = esc(props.heading);
  const bodyLeft   = esc(props.body);
  const bodyRight  = esc(props.bodyRight);
  return `<section class="opollo-Content opollo-Content--two-column" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2 opollo-Content__two-col-heading">${heading}</h2>` : ''}
    <div class="opollo-Content__cols">
      <div class="opollo-Content__col">${bodyLeft ? `<p>${bodyLeft}</p>` : ''}</div>
      <div class="opollo-Content__col">${bodyRight ? `<p>${bodyRight}</p>` : ''}</div>
    </div>
  </div>
</section>`;
}

function renderContentWithImage(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const body    = esc(props.body);
  const img     = props.image as ImageShape | undefined;
  const imgHtml = img?.url
    ? `<img src="${esc(img.url)}" alt="${esc(img.alt ?? '')}" class="opollo-img" loading="lazy">`
    : `<div class="opollo-img-placeholder" aria-hidden="true"></div>`;
  return `<section class="opollo-Content opollo-Content--with-image" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-Content__split">
      <div class="opollo-Content__text">
        ${heading ? `<h2 class="opollo-h2">${heading}</h2>` : ''}
        ${body ? `<div class="opollo-Content__body"><p>${body}</p></div>` : ''}
      </div>
      <div class="opollo-Content__media">${imgHtml}</div>
    </div>
  </div>
</section>`;
}

// ─── TESTIMONIAL ─────────────────────────────────────────────────────────────

function renderTestimonialSingle(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  // Single variant: use first item from embedded array, or resolved single testimonial
  const ts      = asArray<TestimonialShape>(props.testimonials);
  const t       = ts[0] ?? (props.testimonial as TestimonialShape | undefined);
  const quote   = esc(t?.quote ?? '');
  const author  = esc(t?.author ?? '');
  const role    = esc(t?.role ?? '');
  const company = esc(t?.company ?? '');
  const byline  = [role, company].filter(Boolean).join(', ');
  return `<section class="opollo-Testimonial opollo-Testimonial--single" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2 opollo-Testimonial__heading">${heading}</h2>` : ''}
    <figure class="opollo-Testimonial__figure">
      <blockquote class="opollo-Testimonial__quote"><p>${quote}</p></blockquote>
      <figcaption class="opollo-Testimonial__caption">
        <cite class="opollo-Testimonial__author">${author}</cite>${byline ? `\n        <span class="opollo-Testimonial__role">${byline}</span>` : ''}
      </figcaption>
    </figure>
  </div>
</section>`;
}

function renderTestimonialGrid(props: Record<string, unknown>, _t: RenderTarget): string {
  const id           = esc(props.id);
  const heading      = esc(props.heading);
  const testimonials = asArray<TestimonialShape>(props.testimonials);
  const items = testimonials.map(t => {
    const quote   = esc(t.quote ?? '');
    const author  = esc(t.author ?? '');
    const role    = esc(t.role ?? '');
    const company = esc(t.company ?? '');
    const byline  = [role, company].filter(Boolean).join(', ');
    return `      <li class="opollo-Testimonial__card">
        <figure>
          <blockquote class="opollo-Testimonial__card-quote"><p>${quote}</p></blockquote>
          <figcaption class="opollo-Testimonial__card-caption">
            <cite class="opollo-Testimonial__author">${author}</cite>${byline ? `\n            <span class="opollo-Testimonial__role">${byline}</span>` : ''}
          </figcaption>
        </figure>
      </li>`;
  }).join('\n');
  return `<section class="opollo-Testimonial opollo-Testimonial--grid" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2 opollo-Testimonial__heading">${heading}</h2>` : ''}
    <ul class="opollo-Testimonial__grid" role="list">
${items}
    </ul>
  </div>
</section>`;
}

// ─── FAQ ─────────────────────────────────────────────────────────────────────

function renderFAQAccordion(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const faqs    = asArray<FaqShape>(props.faqs);
  const items   = faqs.map(f => `      <details class="opollo-FAQ__item">
        <summary class="opollo-FAQ__question">${esc(f.question ?? '')}</summary>
        <div class="opollo-FAQ__answer"><p>${esc(f.answer ?? '')}</p></div>
      </details>`).join('\n');
  return `<section class="opollo-FAQ opollo-FAQ--accordion" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2">${heading}</h2>` : ''}
    <div class="opollo-FAQ__list">
${items}
    </div>
  </div>
</section>`;
}

function renderFAQList(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const faqs    = asArray<FaqShape>(props.faqs);
  const items   = faqs.map(f => `      <div class="opollo-FAQ__item opollo-FAQ__item--list">
        <dt class="opollo-FAQ__question">${esc(f.question ?? '')}</dt>
        <dd class="opollo-FAQ__answer">${esc(f.answer ?? '')}</dd>
      </div>`).join('\n');
  return `<section class="opollo-FAQ opollo-FAQ--list" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2">${heading}</h2>` : ''}
    <dl class="opollo-FAQ__list opollo-FAQ__list--dl">
${items}
    </dl>
  </div>
</section>`;
}

// ─── STATS ───────────────────────────────────────────────────────────────────

function statItems(stats: StatShape[]): string {
  return stats.map(s => `      <li class="opollo-Stats__item">
        <span class="opollo-Stats__value">${esc(s.value ?? '')}</span>
        <span class="opollo-Stats__label">${esc(s.label ?? '')}</span>
      </li>`).join('\n');
}

function renderStatsHorizontal(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const stats   = asArray<StatShape>(props.stats);
  return `<section class="opollo-Stats opollo-Stats--horizontal" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2 opollo-Stats__heading">${heading}</h2>` : ''}
    <ul class="opollo-Stats__list opollo-Stats__list--horizontal" role="list">
${statItems(stats)}
    </ul>
  </div>
</section>`;
}

function renderStatsGrid(props: Record<string, unknown>, _t: RenderTarget): string {
  const id      = esc(props.id);
  const heading = esc(props.heading);
  const stats   = asArray<StatShape>(props.stats);
  return `<section class="opollo-Stats opollo-Stats--grid" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2 opollo-Stats__heading">${heading}</h2>` : ''}
    <ul class="opollo-Stats__list opollo-Stats__list--grid" role="list">
${statItems(stats)}
    </ul>
  </div>
</section>`;
}

// ─── CONTACT ─────────────────────────────────────────────────────────────────

function contactDetails(email: string, phone: string, address: string): string {
  const items: string[] = [];
  if (email)   items.push(`<li class="opollo-Contact__detail-item"><span class="opollo-Contact__detail-label">Email</span><a href="mailto:${esc(email)}">${esc(email)}</a></li>`);
  if (phone)   items.push(`<li class="opollo-Contact__detail-item"><span class="opollo-Contact__detail-label">Phone</span><a href="tel:${esc(phone)}">${esc(phone)}</a></li>`);
  if (address) items.push(`<li class="opollo-Contact__detail-item"><span class="opollo-Contact__detail-label">Address</span><address class="opollo-Contact__address">${esc(address)}</address></li>`);
  return items.length ? `<ul class="opollo-Contact__details">\n        ${items.join('\n        ')}\n      </ul>` : '';
}

function renderContactForm(props: Record<string, unknown>, _t: RenderTarget): string {
  const id         = esc(props.id);
  const heading    = esc(props.heading);
  const subheading = esc(props.subheading);
  const email      = String(props.email ?? '');
  const phone      = String(props.phone ?? '');
  const address    = String(props.address ?? '');
  const details    = contactDetails(email, phone, address);
  return `<section class="opollo-Contact opollo-Contact--form" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    <div class="opollo-Contact__split">
      <div class="opollo-Contact__info">
        ${heading ? `<h2 class="opollo-h2">${heading}</h2>` : ''}
        ${subheading ? `<p class="opollo-lead">${subheading}</p>` : ''}
        ${details}
      </div>
      <div class="opollo-Contact__form-wrap">
        <form class="opollo-Contact__form" method="post" action="#">
          <label class="opollo-Contact__label" for="name-${id}">Name</label>
          <input class="opollo-Contact__input" type="text" id="name-${id}" name="name" required autocomplete="name">
          <label class="opollo-Contact__label" for="email-${id}">Email</label>
          <input class="opollo-Contact__input" type="email" id="email-${id}" name="email" required autocomplete="email">
          <label class="opollo-Contact__label" for="message-${id}">Message</label>
          <textarea class="opollo-Contact__input opollo-Contact__textarea" id="message-${id}" name="message" rows="5" required></textarea>
          <button type="submit" class="opollo-btn opollo-btn--primary opollo-Contact__submit">Send message</button>
        </form>
      </div>
    </div>
  </div>
</section>`;
}

function renderContactDetails(props: Record<string, unknown>, _t: RenderTarget): string {
  const id         = esc(props.id);
  const heading    = esc(props.heading);
  const subheading = esc(props.subheading);
  const email      = String(props.email ?? '');
  const phone      = String(props.phone ?? '');
  const address    = String(props.address ?? '');
  const details    = contactDetails(email, phone, address);
  return `<section class="opollo-Contact opollo-Contact--details" data-opollo-id="${id}">
  <div class="opollo-container opollo-section-padding">
    ${heading ? `<h2 class="opollo-h2">${heading}</h2>` : ''}
    ${subheading ? `<p class="opollo-lead">${subheading}</p>` : ''}
    ${details}
  </div>
</section>`;
}

// ─── REGISTRY ─────────────────────────────────────────────────────────────────

export const componentRegistry: ComponentRegistry = {

  Hero: {
    'centered': {
      fields:       heroFields,
      defaultProps: { headline: '', subheadline: '', variant: 'centered', ctaVariant: 'primary' },
      render:       renderHeroCentered,
    },
    'split-right': {
      fields:       heroFields,
      defaultProps: { headline: '', subheadline: '', variant: 'split-right', ctaVariant: 'primary' },
      render:       renderHeroSplitRight,
    },
    'split-left': {
      fields:       heroFields,
      defaultProps: { headline: '', subheadline: '', variant: 'split-left', ctaVariant: 'primary' },
      render:       renderHeroSplitLeft,
    },
  },

  Features: {
    'grid-3': {
      fields:       featuresFields,
      defaultProps: { heading: '', subheading: '', variant: 'grid-3', features: [] },
      render:       renderFeaturesGrid3,
    },
    'grid-2': {
      fields:       featuresFields,
      defaultProps: { heading: '', subheading: '', variant: 'grid-2', features: [] },
      render:       renderFeaturesGrid2,
    },
    'list': {
      fields:       featuresFields,
      defaultProps: { heading: '', subheading: '', variant: 'list', features: [] },
      render:       renderFeaturesList,
    },
  },

  CTABanner: {
    'full-width': {
      fields:       ctaBannerFields,
      defaultProps: { heading: '', subheading: '', variant: 'full-width' },
      render:       renderCTABannerFullWidth,
    },
    'card': {
      fields:       ctaBannerFields,
      defaultProps: { heading: '', subheading: '', variant: 'card' },
      render:       renderCTABannerCard,
    },
    'inline': {
      fields:       ctaBannerFields,
      defaultProps: { heading: '', subheading: '', variant: 'inline' },
      render:       renderCTABannerInline,
    },
  },

  Content: {
    'prose': {
      fields:       contentFields,
      defaultProps: { heading: '', body: '', bodyRight: '', variant: 'prose' },
      render:       renderContentProse,
    },
    'two-column': {
      fields:       contentFields,
      defaultProps: { heading: '', body: '', bodyRight: '', variant: 'two-column' },
      render:       renderContentTwoColumn,
    },
    'with-image': {
      fields:       contentFields,
      defaultProps: { heading: '', body: '', bodyRight: '', variant: 'with-image' },
      render:       renderContentWithImage,
    },
  },

  Testimonial: {
    'single': {
      fields:       testimonialFields,
      defaultProps: { heading: '', variant: 'single', testimonials: [] },
      render:       renderTestimonialSingle,
    },
    'grid': {
      fields:       testimonialFields,
      defaultProps: { heading: '', variant: 'grid', testimonials: [] },
      render:       renderTestimonialGrid,
    },
  },

  FAQ: {
    'accordion': {
      fields:       faqFields,
      defaultProps: { heading: '', variant: 'accordion' },
      render:       renderFAQAccordion,
    },
    'list': {
      fields:       faqFields,
      defaultProps: { heading: '', variant: 'list' },
      render:       renderFAQList,
    },
  },

  Stats: {
    'horizontal': {
      fields:       statsFields,
      defaultProps: { heading: '', stats: [], variant: 'horizontal' },
      render:       renderStatsHorizontal,
    },
    'grid': {
      fields:       statsFields,
      defaultProps: { heading: '', stats: [], variant: 'grid' },
      render:       renderStatsGrid,
    },
  },

  Contact: {
    'form': {
      fields:       contactFields,
      defaultProps: { heading: '', subheading: '', email: '', phone: '', address: '', variant: 'form' },
      render:       renderContactForm,
    },
    'details': {
      fields:       contactFields,
      defaultProps: { heading: '', subheading: '', email: '', phone: '', address: '', variant: 'details' },
      render:       renderContactDetails,
    },
  },

};

// ─── MANIFEST FOR LLM PROMPT ──────────────────────────────────────────────
// Compact summary of the registry sent to Haiku in Pass 2.

export const COMPONENT_MANIFEST = [
  { type: 'Hero',        variant: 'centered',    description: 'Large centred headline with CTA button, no image or image below fold',  requiredProps: ['headline'],                       optionalProps: ['subheadline'],              acceptsRefs: ['cta', 'image'] },
  { type: 'Hero',        variant: 'split-right', description: 'Headline left, image right, CTA below headline',                        requiredProps: ['headline'],                       optionalProps: ['subheadline'],              acceptsRefs: ['cta', 'image'] },
  { type: 'Hero',        variant: 'split-left',  description: 'Image left, headline right, CTA below headline',                        requiredProps: ['headline'],                       optionalProps: ['subheadline'],              acceptsRefs: ['cta', 'image'] },
  { type: 'Features',    variant: 'grid-3',      description: '3-column grid of features with icon, title, and description',           requiredProps: ['heading', 'features'],            optionalProps: ['subheading'],               acceptsRefs: [] },
  { type: 'Features',    variant: 'grid-2',      description: '2-column grid of features with icon, title, and description',           requiredProps: ['heading', 'features'],            optionalProps: ['subheading'],               acceptsRefs: [] },
  { type: 'Features',    variant: 'list',        description: 'Vertical list of features with icon and description',                   requiredProps: ['heading', 'features'],            optionalProps: ['subheading'],               acceptsRefs: [] },
  { type: 'CTABanner',   variant: 'full-width',  description: 'Full-width coloured banner with heading and CTA button',                requiredProps: ['heading'],                        optionalProps: ['subheading'],               acceptsRefs: ['cta'] },
  { type: 'CTABanner',   variant: 'card',        description: 'Contained card with heading, subheading, and CTA button',               requiredProps: ['heading'],                        optionalProps: ['subheading'],               acceptsRefs: ['cta'] },
  { type: 'CTABanner',   variant: 'inline',      description: 'Compact inline CTA with text and button on one line',                   requiredProps: ['heading'],                        optionalProps: [],                           acceptsRefs: ['cta'] },
  { type: 'Content',     variant: 'prose',       description: 'Centred prose block for long-form text content',                        requiredProps: ['heading', 'body'],                optionalProps: [],                           acceptsRefs: [] },
  { type: 'Content',     variant: 'two-column',  description: 'Two-column text block; body on left, bodyRight on right',               requiredProps: ['heading', 'body', 'bodyRight'],   optionalProps: [],                           acceptsRefs: [] },
  { type: 'Content',     variant: 'with-image',  description: 'Text block with supporting image on the side',                          requiredProps: ['heading', 'body'],                optionalProps: [],                           acceptsRefs: ['image'] },
  { type: 'Testimonial', variant: 'single',      description: 'One large blockquote testimonial with author attribution',              requiredProps: ['heading'],                        optionalProps: ['testimonials'],             acceptsRefs: ['testimonial'] },
  { type: 'Testimonial', variant: 'grid',        description: '3-column grid of testimonial quotes from testimonials array',           requiredProps: ['heading', 'testimonials'],        optionalProps: [],                           acceptsRefs: [] },
  { type: 'FAQ',         variant: 'accordion',   description: 'Collapsible accordion FAQ; faqs prop populated by ref-resolver',        requiredProps: ['heading'],                        optionalProps: [],                           acceptsRefs: ['faqs'] },
  { type: 'FAQ',         variant: 'list',        description: 'Plain stacked list of FAQ pairs; faqs prop populated by ref-resolver',  requiredProps: ['heading'],                        optionalProps: [],                           acceptsRefs: ['faqs'] },
  { type: 'Stats',       variant: 'horizontal',  description: 'Horizontal row of 3-4 key statistics with value and label',             requiredProps: ['heading', 'stats'],               optionalProps: [],                           acceptsRefs: [] },
  { type: 'Stats',       variant: 'grid',        description: 'Grid layout of statistics — use for 4-6 stats',                         requiredProps: ['heading', 'stats'],               optionalProps: [],                           acceptsRefs: [] },
  { type: 'Contact',     variant: 'form',        description: 'Contact form with name, email, message, plus contact details',          requiredProps: ['heading'],                        optionalProps: ['subheading', 'email', 'phone', 'address'], acceptsRefs: [] },
  { type: 'Contact',     variant: 'details',     description: 'Contact details only (address, phone, email) without a form',           requiredProps: ['heading'],                        optionalProps: ['subheading', 'email', 'phone', 'address'], acceptsRefs: [] },
];
