/**
 * lib/component-registry.ts
 *
 * The complete component library for Opollo site generation.
 * 8 component types. 20 variants total. This is the complete v1 list.
 * No additions without a milestone decision.
 *
 * Field schemas are copied from payloadcms/payload website template blocks:
 * https://github.com/payloadcms/payload/tree/main/templates/website/src/payload/blocks
 * Adaptation: Payload-specific field types replaced with Opollo Field types.
 *
 * Render functions are populated from HyperUI (https://www.hyperui.dev):
 * MIT license. Build Hero/centered end-to-end first. Lock the pattern.
 * Copy the pattern for all 19 remaining variants.
 * DO NOT parallelise the HyperUI copy step — inconsistency guaranteed.
 *
 * CSS class naming: opollo-{ComponentType} opollo-{ComponentType}--{variant}
 * CSS classes are NEVER generated by the LLM.
 * All render functions use CSS variables, never inline styles or Tailwind.
 */

import type { ComponentRegistry, Fields, RenderTarget } from './types/page-document';

// ─── FIELD SCHEMAS (from Payload Website Template) ────────────────────────

const heroFields: Fields = {
  headline:    { type: 'text',     label: 'Headline' },
  subheadline: { type: 'textarea', label: 'Subheadline' },
  variant:     { type: 'radio',    label: 'Layout variant',
                 options: [
                   { label: 'Centred',      value: 'centered'    },
                   { label: 'Image right',  value: 'split-right' },
                   { label: 'Image left',   value: 'split-left'  },
                 ]},
  ctaVariant:  { type: 'select',   label: 'CTA button style',
                 options: [
                   { label: 'Primary', value: 'primary' },
                   { label: 'Ghost',   value: 'ghost'   },
                 ]},
};

const featuresFields: Fields = {
  heading:    { type: 'text',     label: 'Section heading' },
  subheading: { type: 'textarea', label: 'Subheading' },
  variant:    { type: 'radio',    label: 'Layout',
                options: [
                  { label: '3-column grid', value: 'grid-3' },
                  { label: '2-column grid', value: 'grid-2' },
                  { label: 'List',          value: 'list'   },
                ]},
  features: { type: 'array', label: 'Features',
              arrayFields: {
                title:       { type: 'text',     label: 'Title'       },
                description: { type: 'textarea', label: 'Description' },
                iconSlug:    { type: 'text',     label: 'Icon slug (e.g. "star", "check")' },
              }},
};

const ctaBannerFields: Fields = {
  heading:    { type: 'text',     label: 'Heading'    },
  subheading: { type: 'textarea', label: 'Subheading' },
  variant:    { type: 'radio',    label: 'Layout',
                options: [
                  { label: 'Full width', value: 'full-width' },
                  { label: 'Card',       value: 'card'       },
                  { label: 'Inline',     value: 'inline'     },
                ]},
};

const contentFields: Fields = {
  heading:  { type: 'text',     label: 'Heading'   },
  body:     { type: 'textarea', label: 'Body text' },
  variant:  { type: 'radio',    label: 'Layout',
              options: [
                { label: 'Prose',       value: 'prose'      },
                { label: 'Two column',  value: 'two-column' },
                { label: 'With image',  value: 'with-image' },
              ]},
};

const testimonialFields: Fields = {
  heading:  { type: 'text',  label: 'Section heading' },
  variant:  { type: 'radio', label: 'Layout',
              options: [
                { label: 'Single large quote', value: 'single' },
                { label: '3-column grid',      value: 'grid'   },
              ]},
};

const faqFields: Fields = {
  heading:  { type: 'text',  label: 'Section heading' },
  variant:  { type: 'radio', label: 'Layout',
              options: [
                { label: 'Accordion', value: 'accordion' },
                { label: 'List',      value: 'list'      },
              ]},
};

const statsFields: Fields = {
  heading:  { type: 'text',  label: 'Section heading' },
  variant:  { type: 'radio', label: 'Layout',
              options: [
                { label: 'Horizontal row', value: 'horizontal' },
                { label: 'Grid',           value: 'grid'       },
              ]},
  stats: { type: 'array', label: 'Stats',
           arrayFields: {
             value:  { type: 'text', label: 'Value (e.g. "98%" or "10k+")' },
             label:  { type: 'text', label: 'Label (e.g. "Client satisfaction")' },
           }},
};

const contactFields: Fields = {
  heading:    { type: 'text',     label: 'Heading'    },
  subheading: { type: 'textarea', label: 'Subheading' },
  variant:    { type: 'radio',    label: 'Layout',
                options: [
                  { label: 'Contact form + details', value: 'form'    },
                  { label: 'Contact details only',   value: 'details' },
                ]},
};

// ─── RENDER FUNCTIONS ─────────────────────────────────────────────────────
//
// BUILD PROTOCOL:
// 1. Build Hero/centered first, end-to-end (fields → HTML → CSS → tests)
// 2. Lock the pattern from Hero/centered
// 3. Copy the pattern for all 19 remaining variants
// DO NOT start a second variant until Hero/centered is fully working.
//
// SOURCE: https://www.hyperui.dev/components/marketing (MIT)
// For each variant: go to the URL, click Code, copy HTML, adapt:
//   - Replace hardcoded text with ${props.fieldName}
//   - Replace Tailwind colour classes with CSS variables
//   - Wrap with: <div class="opollo-{Type} opollo-{Type}--{variant}" data-opollo-id="${sectionId}">
//
// CSS variable mapping (Tailwind → CSS var):
//   bg-indigo-600 / bg-blue-600  → background-color: var(--opollo-color-primary)
//   text-indigo-600              → color: var(--opollo-color-primary)
//   text-gray-900                → color: var(--opollo-color-text)
//   text-gray-600 / text-gray-500→ color: var(--opollo-color-muted)
//   bg-gray-50 / bg-white        → background-color: var(--opollo-color-bg-alt)
//   border-gray-200              → border-color: var(--opollo-color-border)

type RenderFn = (props: Record<string, unknown>, target: RenderTarget) => string;

// Placeholder until HyperUI step completes.
// Throws with a clear message so any missed TODO is caught immediately.
function TODO(componentKey: string): RenderFn {
  return () => {
    throw new Error(
      `[component-registry] render function not yet implemented for: ${componentKey}\n` +
      `Go to https://www.hyperui.dev/components/marketing and copy the HTML.`
    );
  };
}

// ─── REGISTRY ─────────────────────────────────────────────────────────────

export const componentRegistry: ComponentRegistry = {

  Hero: {
    'centered': {
      fields:       heroFields,
      defaultProps: { headline: '', subheadline: '', variant: 'centered', ctaVariant: 'primary' },
      render:       TODO('Hero:centered'),
      // TODO: go to https://www.hyperui.dev/components/marketing/heroes
      // Pick the centred hero (headline + subtext + CTA button, image optional below fold)
    },
    'split-right': {
      fields:       heroFields,
      defaultProps: { headline: '', subheadline: '', variant: 'split-right', ctaVariant: 'primary' },
      render:       TODO('Hero:split-right'),
      // TODO: go to https://www.hyperui.dev/components/marketing/heroes
      // Pick a split hero layout with image on the right
    },
    'split-left': {
      fields:       heroFields,
      defaultProps: { headline: '', subheadline: '', variant: 'split-left', ctaVariant: 'primary' },
      render:       TODO('Hero:split-left'),
      // Mirror of split-right (swap image/text columns)
    },
  },

  Features: {
    'grid-3': {
      fields:       featuresFields,
      defaultProps: { heading: '', subheading: '', variant: 'grid-3', features: [] },
      render:       TODO('Features:grid-3'),
      // TODO: https://www.hyperui.dev/components/marketing/features → 3-column icon grid
    },
    'grid-2': {
      fields:       featuresFields,
      defaultProps: { heading: '', subheading: '', variant: 'grid-2', features: [] },
      render:       TODO('Features:grid-2'),
      // TODO: https://www.hyperui.dev/components/marketing/features → 2-column grid
    },
    'list': {
      fields:       featuresFields,
      defaultProps: { heading: '', subheading: '', variant: 'list', features: [] },
      render:       TODO('Features:list'),
      // TODO: https://www.hyperui.dev/components/marketing/features → stacked list with icons
    },
  },

  CTABanner: {
    'full-width': {
      fields:       ctaBannerFields,
      defaultProps: { heading: '', subheading: '', variant: 'full-width' },
      render:       TODO('CTABanner:full-width'),
      // TODO: https://www.hyperui.dev/components/marketing/cta → full-width banner with button
    },
    'card': {
      fields:       ctaBannerFields,
      defaultProps: { heading: '', subheading: '', variant: 'card' },
      render:       TODO('CTABanner:card'),
      // TODO: https://www.hyperui.dev/components/marketing/cta → contained card CTA
    },
    'inline': {
      fields:       ctaBannerFields,
      defaultProps: { heading: '', subheading: '', variant: 'inline' },
      render:       TODO('CTABanner:inline'),
      // TODO: https://www.hyperui.dev/components/marketing/cta → compact inline CTA
    },
  },

  Content: {
    'prose': {
      fields:       contentFields,
      defaultProps: { heading: '', body: '', variant: 'prose' },
      render:       TODO('Content:prose'),
      // TODO: https://www.hyperui.dev/components/marketing/content → centred prose block
    },
    'two-column': {
      fields:       contentFields,
      defaultProps: { heading: '', body: '', variant: 'two-column' },
      render:       TODO('Content:two-column'),
      // TODO: https://www.hyperui.dev/components/marketing/content → two-column text
    },
    'with-image': {
      fields:       contentFields,
      defaultProps: { heading: '', body: '', variant: 'with-image' },
      render:       TODO('Content:with-image'),
      // TODO: https://www.hyperui.dev/components/marketing/content → text + image side by side
    },
  },

  Testimonial: {
    'single': {
      fields:       testimonialFields,
      defaultProps: { heading: '', variant: 'single' },
      render:       TODO('Testimonial:single'),
      // TODO: https://www.hyperui.dev/components/marketing/testimonials → single large blockquote
    },
    'grid': {
      fields:       testimonialFields,
      defaultProps: { heading: '', variant: 'grid' },
      render:       TODO('Testimonial:grid'),
      // TODO: https://www.hyperui.dev/components/marketing/testimonials → 3-column grid
    },
  },

  FAQ: {
    'accordion': {
      fields:       faqFields,
      defaultProps: { heading: '', variant: 'accordion' },
      render:       TODO('FAQ:accordion'),
      // TODO: https://www.hyperui.dev/components/marketing/faq → accordion FAQ
    },
    'list': {
      fields:       faqFields,
      defaultProps: { heading: '', variant: 'list' },
      render:       TODO('FAQ:list'),
      // TODO: https://www.hyperui.dev/components/marketing/faq → plain list FAQ
    },
  },

  Stats: {
    'horizontal': {
      fields:       statsFields,
      defaultProps: { heading: '', stats: [], variant: 'horizontal' },
      render:       TODO('Stats:horizontal'),
      // TODO: https://www.hyperui.dev/components/marketing/stats → horizontal stat row
    },
    'grid': {
      fields:       statsFields,
      defaultProps: { heading: '', stats: [], variant: 'grid' },
      render:       TODO('Stats:grid'),
      // TODO: https://www.hyperui.dev/components/marketing/stats → 2×2 or 3-col grid
    },
  },

  Contact: {
    'form': {
      fields:       contactFields,
      defaultProps: { heading: '', subheading: '', variant: 'form' },
      render:       TODO('Contact:form'),
      // TODO: https://www.hyperui.dev/components/marketing/contact → form with name/email/message
    },
    'details': {
      fields:       contactFields,
      defaultProps: { heading: '', subheading: '', variant: 'details' },
      render:       TODO('Contact:details'),
      // TODO: https://www.hyperui.dev/components/marketing/contact → contact details list
    },
  },

};

// ─── MANIFEST FOR LLM PROMPT ──────────────────────────────────────────────
// Compact summary of the registry sent to Haiku in Pass 2.
// descriptions are one sentence — enough for the LLM to make the right choice.

export const COMPONENT_MANIFEST = [
  { type: 'Hero',        variant: 'centered',    description: 'Large centred headline with CTA button, no image or image below fold', requiredProps: ['headline'],         optionalProps: ['subheadline'], acceptsRefs: ['ctaRef', 'imageRef'] },
  { type: 'Hero',        variant: 'split-right', description: 'Headline left, image right, CTA below headline',                       requiredProps: ['headline'],         optionalProps: ['subheadline'], acceptsRefs: ['ctaRef', 'imageRef'] },
  { type: 'Hero',        variant: 'split-left',  description: 'Image left, headline right, CTA below headline',                       requiredProps: ['headline'],         optionalProps: ['subheadline'], acceptsRefs: ['ctaRef', 'imageRef'] },
  { type: 'Features',    variant: 'grid-3',      description: '3-column grid of features with icon, title, and description',          requiredProps: ['heading','features'],optionalProps: ['subheading'],  acceptsRefs: [] },
  { type: 'Features',    variant: 'grid-2',      description: '2-column grid of features with icon, title, and description',          requiredProps: ['heading','features'],optionalProps: ['subheading'],  acceptsRefs: [] },
  { type: 'Features',    variant: 'list',        description: 'Vertical list of features with icon and description',                  requiredProps: ['heading','features'],optionalProps: ['subheading'],  acceptsRefs: [] },
  { type: 'CTABanner',   variant: 'full-width',  description: 'Full-width coloured banner with heading and CTA button',               requiredProps: ['heading'],          optionalProps: ['subheading'],  acceptsRefs: ['ctaRef'] },
  { type: 'CTABanner',   variant: 'card',        description: 'Contained card with heading, subheading, and CTA button',              requiredProps: ['heading'],          optionalProps: ['subheading'],  acceptsRefs: ['ctaRef'] },
  { type: 'CTABanner',   variant: 'inline',      description: 'Compact inline CTA with text and button on one line',                  requiredProps: ['heading'],          optionalProps: [],              acceptsRefs: ['ctaRef'] },
  { type: 'Content',     variant: 'prose',       description: 'Centred prose block for long-form text content',                       requiredProps: ['heading','body'],   optionalProps: [],              acceptsRefs: [] },
  { type: 'Content',     variant: 'two-column',  description: 'Two-column text block for comparing or listing information',           requiredProps: ['heading','body'],   optionalProps: [],              acceptsRefs: [] },
  { type: 'Content',     variant: 'with-image',  description: 'Text block with supporting image on the side',                         requiredProps: ['heading','body'],   optionalProps: [],              acceptsRefs: ['imageRef'] },
  { type: 'Testimonial', variant: 'single',      description: 'One large blockquote testimonial with author attribution',             requiredProps: ['heading'],          optionalProps: [],              acceptsRefs: ['testimonialRef'] },
  { type: 'Testimonial', variant: 'grid',        description: '3-column grid of testimonial quotes',                                  requiredProps: ['heading'],          optionalProps: [],              acceptsRefs: ['testimonialRef'] },
  { type: 'FAQ',         variant: 'accordion',   description: 'Collapsible accordion FAQ with question/answer pairs',                 requiredProps: ['heading'],          optionalProps: [],              acceptsRefs: ['faqRefs'] },
  { type: 'FAQ',         variant: 'list',        description: 'Plain stacked list of FAQ question/answer pairs',                      requiredProps: ['heading'],          optionalProps: [],              acceptsRefs: ['faqRefs'] },
  { type: 'Stats',       variant: 'horizontal',  description: 'Horizontal row of 3-4 key statistics with value and label',            requiredProps: ['heading','stats'],  optionalProps: [],              acceptsRefs: [] },
  { type: 'Stats',       variant: 'grid',        description: 'Grid layout of statistics — use for 4-6 stats',                        requiredProps: ['heading','stats'],  optionalProps: [],              acceptsRefs: [] },
  { type: 'Contact',     variant: 'form',        description: 'Contact form with name, email, message, plus contact details',         requiredProps: ['heading'],          optionalProps: ['subheading'],  acceptsRefs: [] },
  { type: 'Contact',     variant: 'details',     description: 'Contact details only (address, phone, email) without a form',          requiredProps: ['heading'],          optionalProps: ['subheading'],  acceptsRefs: [] },
];
