import { getServiceRoleClient } from "@/lib/supabase";
import { seedAuthUser, signInAs, type SeededAuthUser } from "./_auth-helpers";

// ---------------------------------------------------------------------------
// Security test factories — cross-tenant scenarios.
//
// `seedTwoCompanies` returns a fully-seeded {companyA, companyB} pair
// each with an admin + a member user. Use it to drive route-level
// cross-tenant assertions:
//
//   const { companyA, companyB } = await seedTwoCompanies();
//   const tokenA = await signInAs({ email: companyA.admin.email });
//   // companyA admin tries to read companyB resources — must 403/404.
//
// Why these factories are different from seedAuthUser():
//   - Membership rows in platform_company_users are seeded explicitly
//     so the canDo() permission resolver returns the right answer.
//   - Each company gets an `is_opollo_internal: false` flag — Opollo
//     staff override is a separate test concern.
// ---------------------------------------------------------------------------

export type TestCompany = {
  id: string;
  slug: string;
  admin: SeededAuthUser & { token: string };
  member: SeededAuthUser & { token: string };
};

export type TwoCompanies = {
  companyA: TestCompany;
  companyB: TestCompany;
};

const SEED_PREFIX = `${Date.now()}-${process.pid}`;
let companyCounter = 0;

async function seedOneCompany(label: string): Promise<TestCompany> {
  const svc = getServiceRoleClient();
  const slug = `sec-${label}-${SEED_PREFIX}-${++companyCounter}`;
  // platform_companies.id is generated by the DB. We let it default and
  // read it back so we don't have to manage UUIDs in test code.
  const co = await svc
    .from("platform_companies")
    .insert({
      name: `Sec ${label}`,
      slug,
      domain: `${slug}.test`,
      is_opollo_internal: false,
      timezone: "UTC",
      approval_default_rule: "any_one",
    })
    .select("id, slug")
    .single();
  if (co.error || !co.data) {
    throw new Error(`seedOneCompany(${label}): ${co.error?.message ?? "no data"}`);
  }

  const password = "test-password-1234";
  const adminUser = await seedAuthUser({ password });
  const memberUser = await seedAuthUser({ password });

  const memberRows = await svc.from("platform_company_users").insert([
    {
      company_id: co.data.id,
      user_id: adminUser.id,
      role: "company_admin",
    },
    {
      company_id: co.data.id,
      user_id: memberUser.id,
      role: "company_member",
    },
  ]);
  if (memberRows.error) {
    throw new Error(
      `seedOneCompany(${label}) member rows: ${memberRows.error.message}`,
    );
  }

  const adminToken = await signInAs({ email: adminUser.email, password });
  const memberToken = await signInAs({ email: memberUser.email, password });

  return {
    id: co.data.id as string,
    slug: co.data.slug as string,
    admin: { ...adminUser, token: adminToken },
    member: { ...memberUser, token: memberToken },
  };
}

export async function seedTwoCompanies(): Promise<TwoCompanies> {
  // Sequential, not parallel — emailCounter inside seedAuthUser is
  // not concurrency-safe within a single file's worker, and parallel
  // INSERTs into platform_companies don't buy meaningful speed.
  const companyA = await seedOneCompany("a");
  const companyB = await seedOneCompany("b");
  return { companyA, companyB };
}
