-- 0057 — Optimiser Phase 2 Slice 18: opt_variants + opt_tests.
-- Reference: docs/Optimisation_Engine_Spec_v1.5.docx §6 feature 8, §12.3.
--
-- A/B testing infrastructure deferred from Phase 1. Two new tables:
--
--   opt_variants — one row per generated page version that participates
--   in a test. variant_label = 'A' is the approved-proposal version
--   (the canonical / control); 'B' is the alternative generated by the
--   variant-generation skill. The variant generator may produce more
--   than two siblings in future slices; the schema accepts label up to
--   'D' to leave room without a forward-only ALTER.
--
--   opt_tests — one row per running A/B test. Records the two variants,
--   the traffic split, the §12.3 minimum-sample floors, and the
--   Bayesian winner-probability fields the Slice 19 monitor populates.
--
-- Both tables RLS-scoped per the M2b pattern. Service-role-all + an
-- authenticated read policy gated by public.auth_role().

CREATE TABLE opt_variants (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id                uuid NOT NULL
    REFERENCES opt_clients(id) ON DELETE CASCADE,
  landing_page_id          uuid NOT NULL
    REFERENCES opt_landing_pages(id) ON DELETE CASCADE,
  source_proposal_id       uuid NOT NULL
    REFERENCES opt_proposals(id) ON DELETE CASCADE,

  -- 'A' | 'B' | 'C' | 'D'. Phase 2 default flow ships A + B only;
  -- the wider range is room for future multi-arm tests without a
  -- migration on the CHECK constraint.
  variant_label            text NOT NULL
    CHECK (variant_label IN ('A', 'B', 'C', 'D')),

  -- Site Builder brief / brief_run / page_version that materialised
  -- this variant. NULL while the brief is queued / generating.
  brief_id                 uuid,
  brief_run_id             uuid,
  page_version             text,

  -- The actual change set that distinguishes this variant. For 'A'
  -- this mirrors the source proposal's change_set verbatim. For 'B'
  -- the variant generator emits a structurally distinct alternative
  -- (different hero composition, different CTA placement, different
  -- form length, etc) — recorded here for transparency.
  change_set               jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Free-form note describing why B is structurally distinct from A.
  -- Surfaced in the test status banner for the operator's reference.
  generation_notes         text,

  -- Lifecycle.
  --   queued      → brief submitted, awaiting brief-runner pickup
  --   generating  → brief-runner is composing
  --   ready       → page generated + written; eligible for activation
  --   active      → currently serving traffic in an opt_tests row
  --   superseded  → another variant won; this one is archived
  --   failed      → brief-runner failed terminally
  status                   text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'generating', 'ready', 'active', 'superseded', 'failed')),

  generated_at             timestamptz,
  failed_reason            text,

  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  created_by               uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX opt_variants_proposal_idx
  ON opt_variants (source_proposal_id);
CREATE INDEX opt_variants_client_status_idx
  ON opt_variants (client_id, status);
CREATE INDEX opt_variants_landing_page_idx
  ON opt_variants (landing_page_id, variant_label);

ALTER TABLE opt_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY service_role_all ON opt_variants
  FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY opt_variants_read ON opt_variants
  FOR SELECT TO authenticated
  USING (public.auth_role() IN ('admin', 'operator', 'viewer'));

-- ---------------------------------------------------------------------------
-- opt_tests
-- ---------------------------------------------------------------------------
CREATE TABLE opt_tests (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id                uuid NOT NULL
    REFERENCES opt_clients(id) ON DELETE CASCADE,
  landing_page_id          uuid NOT NULL
    REFERENCES opt_landing_pages(id) ON DELETE CASCADE,
  source_proposal_id       uuid NOT NULL
    REFERENCES opt_proposals(id) ON DELETE CASCADE,

  variant_a_id             uuid NOT NULL
    REFERENCES opt_variants(id) ON DELETE RESTRICT,
  variant_b_id             uuid NOT NULL
    REFERENCES opt_variants(id) ON DELETE RESTRICT,

  -- Percent of traffic routed to variant B. A receives the remainder.
  -- 50 = balanced split; 20 mirrors the §12.2.1 staged-rollout default
  -- if an operator wants to be more conservative.
  traffic_split_percent    integer NOT NULL DEFAULT 50
    CHECK (traffic_split_percent BETWEEN 1 AND 99),

  status                   text NOT NULL DEFAULT 'queued'
    CHECK (status IN (
      'queued', 'running', 'winner_a', 'winner_b', 'inconclusive', 'stopped'
    )),

  -- §12.3 / §9.5 minimum-sample floors before winner detection runs.
  min_sessions             integer NOT NULL DEFAULT 100
    CHECK (min_sessions >= 0),
  min_conversions          integer NOT NULL DEFAULT 10
    CHECK (min_conversions >= 0),

  -- Bayesian posterior outputs from the §6 feature 8 winner detector.
  -- Slice 19 populates these on each cron tick. NULL until enough data.
  winner_probability_a     numeric(4, 3)
    CHECK (winner_probability_a IS NULL OR (winner_probability_a >= 0 AND winner_probability_a <= 1)),
  winner_probability_b     numeric(4, 3)
    CHECK (winner_probability_b IS NULL OR (winner_probability_b >= 0 AND winner_probability_b <= 1)),
  -- Snapshot of the most recent metrics computed by the monitor cron.
  -- Shape: { a: { sessions, conversions, cr }, b: { ... }, evaluated_at }.
  last_metrics_snapshot    jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_evaluated_at        timestamptz,

  started_at               timestamptz,
  ended_at                 timestamptz,
  -- Free-form reason populated when status flips to stopped or
  -- inconclusive (e.g. 'maximum_window_expired', 'operator_aborted').
  ended_reason             text,

  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),

  -- Coherence: A and B can't be the same variant.
  CONSTRAINT opt_tests_distinct_variants CHECK (variant_a_id <> variant_b_id)
);

-- Only one running test per landing page at a time. Phase 2 scope is
-- one A/B per page; Phase 3 may relax for multi-arm tests but that
-- needs a separate UNIQUE-constraint redesign.
CREATE UNIQUE INDEX opt_tests_one_running_per_page_uniq
  ON opt_tests (landing_page_id)
  WHERE status = 'running';

CREATE INDEX opt_tests_client_status_idx
  ON opt_tests (client_id, status);
CREATE INDEX opt_tests_running_idx
  ON opt_tests (status)
  WHERE status = 'running';

ALTER TABLE opt_tests ENABLE ROW LEVEL SECURITY;
CREATE POLICY service_role_all ON opt_tests
  FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY opt_tests_read ON opt_tests
  FOR SELECT TO authenticated
  USING (public.auth_role() IN ('admin', 'operator', 'viewer'));
