-- 0182_feedback_ticket_number.sql
-- Additive: adds ticket_number BIGINT GENERATED ALWAYS AS IDENTITY to
-- feedback_tickets. PostgreSQL fills existing rows with sequential values
-- automatically when the column is added to a non-empty table.
-- The identity sequence starts at 1; concurrent inserts cannot collide
-- (identity columns use a per-table sequence, not advisory locks).
--
-- No change to the title column. Title is now auto-generated server-side
-- from the first line of description — callers should not send it.

ALTER TABLE feedback_tickets
  ADD COLUMN IF NOT EXISTS ticket_number BIGINT GENERATED ALWAYS AS IDENTITY;

COMMENT ON COLUMN feedback_tickets.ticket_number IS
  'Human-friendly sequential ticket identifier (#1, #2, …). Generated by the DB sequence; never set by callers.';
